# -*- encoding: utf-8 -*-

datas = {
    'AD': {'country': 'Andorra, Principality of', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'AE': {'country': 'United Arab Emirates', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'AF': {'country': 'Afghanistan, Islamic State of', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'AG': {'country': 'Antigua and Barbuda', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'AI': {'country': 'Anguilla', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AL': {'country': 'Albania', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AM': {'country': 'Armenia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AN': {'country': 'Netherlands Antilles', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'AO': {'country': 'Angola', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AQ': {'country': 'Antarctica', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 0, 'pos': ''},
    'AR': {'country': 'Argentina', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AS': {'country': 'American Samoa', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AT': {'country': 'Austria', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'AU': {'country': 'Australia', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'AW': {'country': 'Aruba', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'AX': {'country': 'Åland Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'AZ': {'country': 'Azerbaijan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BA': {'country': 'Bosnia-Herzegovina', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'BB': {'country': 'Barbados', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'BD': {'country': 'Bangladesh', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'BE': {'country': 'Belgium', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'BF': {'country': 'Burkina Faso', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 30, 'pos': ''},
    'BG': {'country': 'Bulgaria', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BH': {'country': 'Bahrain', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BI': {'country': 'Burundi', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BJ': {'country': 'Benin', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 30, 'pos': ''},
    'BL': {'country': 'Saint Barthélémy', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'BM': {'country': 'Bermuda', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'BN': {'country': 'Brunei Darussalam', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BO': {'country': 'Bolivia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'BQ': {'country': 'Bonaire, Sint Eustatius and Saba', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'BR': {'country': 'Brazil', 'ar': True, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'BS': {'country': 'Bahamas', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'BT': {'country': 'Bhutan', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'BV': {'country': 'Bouvet Island', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'BW': {'country': 'Botswana', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BY': {'country': 'Belarus', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'BZ': {'country': 'Belize', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 25, 'pos': ''},
    'CA': {'country': 'Canada', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'CC': {'country': 'Cocos (Keeling) Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'CD': {'country': 'Congo, Democratic Republic of the', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'CF': {'country': 'Central African Republic', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'CG': {'country': 'Congo', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 20, 'pos': ''},
    'CH': {'country': 'Switzerland', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'CI': {'country': "Ivory Coast (Cote D'Ivoire)", 'ar': False, 'product': 'CY', 'crbt': 600, 'weight': 30, 'pos': ''},
    'CK': {'country': 'Cook Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'CL': {'country': 'Chile', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'CM': {'country': 'Cameroon', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 30, 'pos': ''},
    'CN': {'country': 'China', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'CO': {'country': 'Colombia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'CR': {'country': 'Costa Rica', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'CU': {'country': 'Cuba', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'CV': {'country': 'Cape Verde', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 20, 'pos': ''},
    'CW': {'country': 'Curaçao', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'CX': {'country': 'Christmas Island', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'CY': {'country': 'Cyprus', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': ''},
    'CZ': {'country': 'Czech Republic', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'DE': {'country': 'Germany', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'DJ': {'country': 'Djibouti', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'DK': {'country': 'Denmark', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'DM': {'country': 'Dominica', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'DO': {'country': 'Dominican Republic', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'DZ': {'country': 'Algeria', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'EC': {'country': 'Ecuador', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'EE': {'country': 'Estonia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'EG': {'country': 'Egypt', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'EH': {'country': 'Western Sahara', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'ER': {'country': 'Eritrea', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'ES': {'country': 'Spain', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'ET': {'country': 'Ethiopia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'FI': {'country': 'Finland', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'FJ': {'country': 'Fiji', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'FK': {'country': 'Falkland Islands', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'FM': {'country': 'Micronesia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'FO': {'country': 'Faroe Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'FR': {'country': 'France', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'GA': {'country': 'Gabon', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 20, 'pos': ''},
    'GB': {'country': 'United Kingdom', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'GD': {'country': 'Grenada', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'GE': {'country': 'Georgia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'GF': {'country': 'French Guyana', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'GG': {'country': 'Guernsey', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'GH': {'country': 'Ghana', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'GI': {'country': 'Gibraltar', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'GL': {'country': 'Greenland', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'GM': {'country': 'Gambia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'GN': {'country': 'Guinea', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'GP': {'country': 'Guadeloupe (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'GQ': {'country': 'Equatorial Guinea', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'GR': {'country': 'Greece', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'GS': {'country': 'South Georgia and the South Sandwich Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'GT': {'country': 'Guatemala', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'GU': {'country': 'Guam (USA)', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'GW': {'country': 'Guinea Bissau', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'GY': {'country': 'Guyana', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'HK': {'country': 'Hong Kong', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'HM': {'country': 'Heard and McDonald Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'HN': {'country': 'Honduras', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'HR': {'country': 'Croatia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'HT': {'country': 'Haiti', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'HU': {'country': 'Hungary', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': ''},
    'ID': {'country': 'Indonesia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'IE': {'country': 'Ireland', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'IL': {'country': 'Israel', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 20, 'pos': 'KPG'},
    'IM': {'country': 'Isle of Man', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'IN': {'country': 'India', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'IO': {'country': 'British Indian Ocean Territory', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'IQ': {'country': 'Iraq', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'IR': {'country': 'Iran', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'IS': {'country': 'Iceland', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'IT': {'country': 'Italy', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'JE': {'country': 'Jersey', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 0, 'pos': ''},
    'JM': {'country': 'Jamaica', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'JO': {'country': 'Jordan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'JP': {'country': 'Japan', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'KE': {'country': 'Kenya', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'KG': {'country': 'Kyrgyz Republic (Kyrgyzstan)', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'KH': {'country': 'Cambodia, Kingdom of', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'KI': {'country': 'Kiribati', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'KM': {'country': 'Comoros', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'KN': {'country': 'Saint Kitts & Nevis Anguilla', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'KP': {'country': 'North Korea', 'ar': True, 'product': 'EY', 'crbt': 0, 'weight': 20, 'pos': 'KPG'},
    'KR': {'country': 'South Korea', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'KW': {'country': 'Kuwait', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'KY': {'country': 'Cayman Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'KZ': {'country': 'Kazakhstan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'LA': {'country': 'Laos', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'LB': {'country': 'Lebanon', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'LC': {'country': 'Saint Lucia', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'LI': {'country': 'Liechtenstein', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': ''},
    'LK': {'country': 'Sri Lanka', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'LR': {'country': 'Liberia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'LS': {'country': 'Lesotho', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'LT': {'country': 'Lithuania', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'LU': {'country': 'Luxembourg', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': 'EPG'},
    'LV': {'country': 'Latvia', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': ''},
    'LY': {'country': 'Libya', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MA': {'country': 'Morocco', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'MC': {'country': 'Monaco', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'MD': {'country': 'Moldavia', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'ME': {'country': 'Montenegro', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MF': {'country': 'Saint Martin (French part)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'MG': {'country': 'Madagascar', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'MH': {'country': 'Marshall Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MK': {'country': 'Macedonia, the former Yugoslav Republic of', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'ML': {'country': 'Mali', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MM': {'country': 'Myanmar', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'MN': {'country': 'Mongolia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MO': {'country': 'Macau', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MP': {'country': 'Northern Mariana Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MQ': {'country': 'Martinique (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'MR': {'country': 'Mauritania', 'ar': False, 'product': 'CY', 'crbt': 600, 'weight': 30, 'pos': ''},
    'MS': {'country': 'Montserrat', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'MT': {'country': 'Malta', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MU': {'country': 'Mauritius', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MV': {'country': 'Maldives', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MW': {'country': 'Malawi', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MX': {'country': 'Mexico', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MY': {'country': 'Malaysia', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'MZ': {'country': 'Mozambique', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'NA': {'country': 'Namibia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'NC': {'country': 'New Caledonia (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'NE': {'country': 'Niger', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'NF': {'country': 'Norfolk Island', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'NG': {'country': 'Nigeria', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'NI': {'country': 'Nicaragua', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'NL': {'country': 'Netherlands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'NO': {'country': 'Norway', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'NP': {'country': 'Nepal', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'NR': {'country': 'Nauru', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'NT': {'country': 'Neutral Zone', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'NU': {'country': 'Niue', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 0, 'pos': ''},
    'NZ': {'country': 'New Zealand', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'OM': {'country': 'Oman', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'PA': {'country': 'Panama', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'PE': {'country': 'Peru', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'PF': {'country': 'Polynesia (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'PG': {'country': 'Papua New Guinea', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 25, 'pos': ''},
    'PH': {'country': 'Philippines', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'PK': {'country': 'Pakistan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'PL': {'country': 'Poland', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'PM': {'country': 'Saint Pierre and Miquelon', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'PN': {'country': 'Pitcairn Island', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 0, 'pos': ''},
    'PR': {'country': 'Puerto Rico', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'PS': {'country': 'Palestinian Territory, Occupied', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'PT': {'country': 'Portugal', 'ar': False, 'product': 'CY', 'crbt': 1000, 'weight': 30, 'pos': 'EPG'},
    'PW': {'country': 'Palau', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'PY': {'country': 'Paraguay', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'QA': {'country': 'Qatar', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'RE': {'country': 'Reunion (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'RO': {'country': 'Romania', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'RS': {'country': 'Serbia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'RU': {'country': 'Russian Federation', 'ar': True, 'product': 'EY', 'crbt': 0, 'weight': 20, 'pos': 'KPG'},
    'RW': {'country': 'Rwanda', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SA': {'country': 'Saudi Arabia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SB': {'country': 'Solomon Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'SC': {'country': 'Seychelles', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SD': {'country': 'Sudan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SE': {'country': 'Sweden', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': 'EPG'},
    'SG': {'country': 'Singapore', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'SH': {'country': 'Saint Helena', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'SI': {'country': 'Slovenia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SJ': {'country': 'Svalbard and Jan Mayen Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'SK': {'country': 'Slovakia', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SL': {'country': 'Sierra Leone', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SM': {'country': 'San Marino', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 20, 'pos': ''},
    'SN': {'country': 'Senegal', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 20, 'pos': ''},
    'SO': {'country': 'Somalia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'SR': {'country': 'Suriname', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'SS': {'country': 'South Sudan', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'ST': {'country': 'Saint Tome (Sao Tome) and Principe', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SV': {'country': 'El Salvador', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'SX': {'country': 'Sint Maarten (Dutch part)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'SY': {'country': 'Syria', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'SZ': {'country': 'Swaziland', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TC': {'country': 'Turks and Caicos Islands', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TD': {'country': 'Chad', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'TF': {'country': 'French Southern Territories', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'TG': {'country': 'Togo', 'ar': True, 'product': 'CY', 'crbt': 600, 'weight': 20, 'pos': ''},
    'TH': {'country': 'Thailand', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'TJ': {'country': 'Tajikistan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TK': {'country': 'Tokelau', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'TM': {'country': 'Turkmenistan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TN': {'country': 'Tunisia', 'ar': False, 'product': 'CY', 'crbt': 1500, 'weight': 30, 'pos': ''},
    'TO': {'country': 'Tonga', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TP': {'country': 'East Timor', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TR': {'country': 'Turkey', 'ar': False, 'product': 'CY', 'crbt': 1000, 'weight': 30, 'pos': ''},
    'TT': {'country': 'Trinidad and Tobago', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TV': {'country': 'Tuvalu', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TW': {'country': 'Taiwan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'TZ': {'country': 'Tanzania', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'UA': {'country': 'Ukraine', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'UG': {'country': 'Uganda', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'UM': {'country': 'USA Minor Outlying Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'US': {'country': 'United States', 'ar': False, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'UY': {'country': 'Uruguay', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'UZ': {'country': 'Uzbekistan', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'VA': {'country': 'Holy See (Vatican City State)', 'ar': True, 'product': 'CY', 'crbt': 1500, 'weight': 20, 'pos': ''},
    'VC': {'country': 'Saint Vincent & Grenadines', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 10, 'pos': ''},
    'VE': {'country': 'Venezuela', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'VG': {'country': 'Virgin Islands (British)', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'VI': {'country': 'Virgin Islands (USA)', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'VN': {'country': 'Vietnam', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'VU': {'country': 'Vanuatu', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 25, 'pos': ''},
    'WF': {'country': 'Wallis and Futuna Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'WS': {'country': 'Samoa', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 20, 'pos': ''},
    'YE': {'country': 'Yemen', 'ar': True, 'product': 'EY', 'crbt': 0, 'weight': 30, 'pos': 'KPG'},
    'YT': {'country': 'Mayotte', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'YU': {'country': 'Yugoslavia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'ZA': {'country': 'South Africa', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'ZM': {'country': 'Zambia', 'ar': True, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
    'ZR': {'country': 'Zaire', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0, 'pos': ''},
    'ZW': {'country': 'Zimbabwe', 'ar': False, 'product': 'CY', 'crbt': 0, 'weight': 30, 'pos': ''},
}
