# -*- encoding: utf-8 -*-

datas = {
    'AD': {'country': 'Andorra, Principality of', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'AE': {'country': 'United Arab Emirates', 'ar': True, 'crbt': 0, 'weight': 30},
    'AF': {'country': 'Afghanistan, Islamic State of', 'ar': True, 'crbt': 0, 'weight': 30},
    'AG': {'country': 'Antigua and Barbuda', 'ar': True, 'crbt': 0, 'weight': 10},
    'AI': {'country': 'Anguilla', 'ar': True, 'crbt': 0, 'weight': 20},
    'AL': {'country': 'Albania', 'ar': True, 'crbt': 0, 'weight': 20},
    'AM': {'country': 'Armenia', 'ar': True, 'crbt': 0, 'weight': 20},
    'AN': {'country': 'Netherlands Antilles', 'ar': True, 'crbt': 0, 'weight': 30},
    'AO': {'country': 'Angola', 'ar': True, 'crbt': 0, 'weight': 20},
    'AQ': {'country': 'Antarctica', 'ar': False, 'crbt': 0, 'weight': 0},
    'AR': {'country': 'Argentina', 'ar': True, 'crbt': 0, 'weight': 20},
    'AS': {'country': 'American Samoa', 'ar': True, 'crbt': 0, 'weight': 20},
    'AT': {'country': 'Austria', 'ar': False, 'crbt': 1500, 'weight': 30},
    'AU': {'country': 'Australia', 'ar': False, 'crbt': 0, 'weight': 30},
    'AW': {'country': 'Aruba', 'ar': True, 'crbt': 0, 'weight': 20},
    'AX': {'country': 'Åland Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'AZ': {'country': 'Azerbaijan', 'ar': True, 'crbt': 0, 'weight': 30},
    'BA': {'country': 'Bosnia-Herzegovina', 'ar': False, 'crbt': 0, 'weight': 20},
    'BB': {'country': 'Barbados', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'BD': {'country': 'Bangladesh', 'ar': False, 'crbt': 0, 'weight': 20},
    'BE': {'country': 'Belgium', 'ar': False, 'crbt': 1500, 'weight': 30},
    'BF': {'country': 'Burkina Faso', 'ar': True, 'crbt': 600, 'weight': 30},
    'BG': {'country': 'Bulgaria', 'ar': True, 'crbt': 0, 'weight': 30},
    'BH': {'country': 'Bahrain', 'ar': True, 'crbt': 0, 'weight': 30},
    'BI': {'country': 'Burundi', 'ar': True, 'crbt': 0, 'weight': 30},
    'BJ': {'country': 'Benin', 'ar': True, 'crbt': 600, 'weight': 30},
    'BL': {'country': 'Saint Barthélémy', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'BM': {'country': 'Bermuda', 'ar': False, 'crbt': 0, 'weight': 20},
    'BN': {'country': 'Brunei Darussalam', 'ar': True, 'crbt': 0, 'weight': 30},
    'BO': {'country': 'Bolivia', 'ar': True, 'crbt': 0, 'weight': 20},
    'BQ': {'country': 'Bonaire, Sint Eustatius and Saba', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'BR': {'country': 'Brazil', 'ar': True, 'crbt': 0, 'weight': 30},
    'BS': {'country': 'Bahamas', 'ar': True, 'crbt': 0, 'weight': 20},
    'BT': {'country': 'Bhutan', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'BV': {'country': 'Bouvet Island', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'BW': {'country': 'Botswana', 'ar': True, 'crbt': 0, 'weight': 30},
    'BY': {'country': 'Belarus', 'ar': True, 'crbt': 0, 'weight': 30},
    'BZ': {'country': 'Belize', 'ar': False, 'crbt': 0, 'weight': 25},
    'CA': {'country': 'Canada', 'ar': False, 'crbt': 0, 'weight': 30},
    'CC': {'country': 'Cocos (Keeling) Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'CD': {'country': 'Congo, Democratic Republic of the', 'ar': True, 'crbt': 0, 'weight': 20},
    'CF': {'country': 'Central African Republic', 'ar': True, 'crbt': 0, 'weight': 20},
    'CG': {'country': 'Congo', 'ar': True, 'crbt': 600, 'weight': 20},
    'CH': {'country': 'Switzerland', 'ar': False, 'crbt': 1500, 'weight': 30},
    'CI': {'country': "Ivory Coast (Cote D'Ivoire)", 'ar': False, 'crbt': 600, 'weight': 30},
    'CK': {'country': 'Cook Islands', 'ar': False, 'crbt': 0, 'weight': 20},
    'CL': {'country': 'Chile', 'ar': True, 'crbt': 0, 'weight': 30},
    'CM': {'country': 'Cameroon', 'ar': True, 'crbt': 600, 'weight': 30},
    'CN': {'country': 'China', 'ar': False, 'crbt': 0, 'weight': 30},
    'CO': {'country': 'Colombia', 'ar': True, 'crbt': 0, 'weight': 30},
    'CR': {'country': 'Costa Rica', 'ar': True, 'crbt': 0, 'weight': 30},
    'CU': {'country': 'Cuba', 'ar': True, 'crbt': 0, 'weight': 10},
    'CV': {'country': 'Cape Verde', 'ar': True, 'crbt': 1500, 'weight': 20},
    'CW': {'country': 'Curaçao', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'CX': {'country': 'Christmas Island', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'CY': {'country': 'Cyprus', 'ar': False, 'crbt': 1500, 'weight': 30},
    'CZ': {'country': 'Czech Republic', 'ar': False, 'crbt': 0, 'weight': 30},
    'DE': {'country': 'Germany', 'ar': False, 'crbt': 1500, 'weight': 30},
    'DJ': {'country': 'Djibouti', 'ar': True, 'crbt': 0, 'weight': 20},
    'DK': {'country': 'Denmark', 'ar': False, 'crbt': 0, 'weight': 30},
    'DM': {'country': 'Dominica', 'ar': False, 'crbt': 0, 'weight': 20},
    'DO': {'country': 'Dominican Republic', 'ar': True, 'crbt': 0, 'weight': 30},
    'DZ': {'country': 'Algeria', 'ar': False, 'crbt': 0, 'weight': 20},
    'EC': {'country': 'Ecuador', 'ar': False, 'crbt': 0, 'weight': 30},
    'EE': {'country': 'Estonia', 'ar': True, 'crbt': 0, 'weight': 30},
    'EG': {'country': 'Egypt', 'ar': True, 'crbt': 0, 'weight': 30},
    'EH': {'country': 'Western Sahara', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'ER': {'country': 'Eritrea', 'ar': True, 'crbt': 0, 'weight': 20},
    'ES': {'country': 'Spain', 'ar': False, 'crbt': 1500, 'weight': 30},
    'ET': {'country': 'Ethiopia', 'ar': True, 'crbt': 0, 'weight': 30},
    'FI': {'country': 'Finland', 'ar': False, 'crbt': 0, 'weight': 30},
    'FJ': {'country': 'Fiji', 'ar': True, 'crbt': 0, 'weight': 20},
    'FK': {'country': 'Falkland Islands', 'ar': True, 'crbt': 0, 'weight': 20},
    'FM': {'country': 'Micronesia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'FO': {'country': 'Faroe Islands', 'ar': False, 'crbt': 0, 'weight': 30},
    'FR': {'country': 'France', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'GA': {'country': 'Gabon', 'ar': True, 'crbt': 600, 'weight': 20},
    'GB': {'country': 'United Kingdom', 'ar': False, 'crbt': 0, 'weight': 30},
    'GD': {'country': 'Grenada', 'ar': False, 'crbt': 0, 'weight': 20},
    'GE': {'country': 'Georgia', 'ar': True, 'crbt': 0, 'weight': 30},
    'GF': {'country': 'French Guyana', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'GG': {'country': 'Guernsey', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'GH': {'country': 'Ghana', 'ar': True, 'crbt': 0, 'weight': 30},
    'GI': {'country': 'Gibraltar', 'ar': True, 'crbt': 0, 'weight': 20},
    'GL': {'country': 'Greenland', 'ar': True, 'crbt': 0, 'weight': 30},
    'GM': {'country': 'Gambia', 'ar': True, 'crbt': 0, 'weight': 30},
    'GN': {'country': 'Guinea', 'ar': True, 'crbt': 0, 'weight': 10},
    'GP': {'country': 'Guadeloupe (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'GQ': {'country': 'Equatorial Guinea', 'ar': True, 'crbt': 0, 'weight': 10},
    'GR': {'country': 'Greece', 'ar': False, 'crbt': 0, 'weight': 30},
    'GS': {'country': 'South Georgia and the South Sandwich Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'GT': {'country': 'Guatemala', 'ar': True, 'crbt': 0, 'weight': 30},
    'GU': {'country': 'Guam (USA)', 'ar': True, 'crbt': 0, 'weight': 10},
    'GW': {'country': 'Guinea Bissau', 'ar': True, 'crbt': 0, 'weight': 20},
    'GY': {'country': 'Guyana', 'ar': True, 'crbt': 0, 'weight': 20},
    'HK': {'country': 'Hong Kong', 'ar': False, 'crbt': 0, 'weight': 30},
    'HM': {'country': 'Heard and McDonald Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'HN': {'country': 'Honduras', 'ar': True, 'crbt': 0, 'weight': 20},
    'HR': {'country': 'Croatia', 'ar': True, 'crbt': 0, 'weight': 30},
    'HT': {'country': 'Haiti', 'ar': True, 'crbt': 0, 'weight': 20},
    'HU': {'country': 'Hungary', 'ar': False, 'crbt': 1500, 'weight': 30},
    'ID': {'country': 'Indonesia', 'ar': True, 'crbt': 0, 'weight': 30},
    'IE': {'country': 'Ireland', 'ar': False, 'crbt': 0, 'weight': 30},
    'IL': {'country': 'Israel', 'ar': False, 'crbt': 0, 'weight': 20},
    'IM': {'country': 'Isle of Man', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'IN': {'country': 'India', 'ar': True, 'crbt': 0, 'weight': 20},
    'IO': {'country': 'British Indian Ocean Territory', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'IQ': {'country': 'Iraq', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'IR': {'country': 'Iran', 'ar': True, 'crbt': 0, 'weight': 20},
    'IS': {'country': 'Iceland', 'ar': True, 'crbt': 1500, 'weight': 30},
    'IT': {'country': 'Italy', 'ar': False, 'crbt': 1500, 'weight': 30},
    'JE': {'country': 'Jersey', 'ar': False, 'crbt': 0, 'weight': 0},
    'JM': {'country': 'Jamaica', 'ar': False, 'crbt': 0, 'weight': 20},
    'JO': {'country': 'Jordan', 'ar': True, 'crbt': 0, 'weight': 30},
    'JP': {'country': 'Japan', 'ar': False, 'crbt': 0, 'weight': 30},
    'KE': {'country': 'Kenya', 'ar': True, 'crbt': 0, 'weight': 30},
    'KG': {'country': 'Kyrgyz Republic (Kyrgyzstan)', 'ar': True, 'crbt': 0, 'weight': 20},
    'KH': {'country': 'Cambodia, Kingdom of', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'KI': {'country': 'Kiribati', 'ar': True, 'crbt': 0, 'weight': 30},
    'KM': {'country': 'Comoros', 'ar': True, 'crbt': 0, 'weight': 20},
    'KN': {'country': 'Saint Kitts & Nevis Anguilla', 'ar': False, 'crbt': 0, 'weight': 20},
    'KP': {'country': 'North Korea', 'ar': True, 'crbt': 0, 'weight': 20},
    'KR': {'country': 'South Korea', 'ar': False, 'crbt': 0, 'weight': 20},
    'KW': {'country': 'Kuwait', 'ar': True, 'crbt': 0, 'weight': 30},
    'KY': {'country': 'Cayman Islands', 'ar': False, 'crbt': 0, 'weight': 10},
    'KZ': {'country': 'Kazakhstan', 'ar': True, 'crbt': 0, 'weight': 20},
    'LA': {'country': 'Laos', 'ar': True, 'crbt': 0, 'weight': 20},
    'LB': {'country': 'Lebanon', 'ar': True, 'crbt': 0, 'weight': 30},
    'LC': {'country': 'Saint Lucia', 'ar': False, 'crbt': 0, 'weight': 20},
    'LI': {'country': 'Liechtenstein', 'ar': True, 'crbt': 1500, 'weight': 30},
    'LK': {'country': 'Sri Lanka', 'ar': True, 'crbt': 0, 'weight': 30},
    'LR': {'country': 'Liberia', 'ar': True, 'crbt': 0, 'weight': 20},
    'LS': {'country': 'Lesotho', 'ar': True, 'crbt': 0, 'weight': 20},
    'LT': {'country': 'Lithuania', 'ar': True, 'crbt': 0, 'weight': 30},
    'LU': {'country': 'Luxembourg', 'ar': False, 'crbt': 1500, 'weight': 30},
    'LV': {'country': 'Latvia', 'ar': True, 'crbt': 1500, 'weight': 30},
    'LY': {'country': 'Libya', 'ar': True, 'crbt': 0, 'weight': 30},
    'MA': {'country': 'Morocco', 'ar': False, 'crbt': 0, 'weight': 30},
    'MC': {'country': 'Monaco', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'MD': {'country': 'Moldavia', 'ar': False, 'crbt': 0, 'weight': 20},
    'ME': {'country': 'Montenegro', 'ar': True, 'crbt': 0, 'weight': 30},
    'MF': {'country': 'Saint Martin (French part)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'MG': {'country': 'Madagascar', 'ar': True, 'crbt': 0, 'weight': 20},
    'MH': {'country': 'Marshall Islands', 'ar': False, 'crbt': 0, 'weight': 30},
    'MK': {'country': 'Macedonia, the former Yugoslav Republic of', 'ar': True, 'crbt': 0, 'weight': 30},
    'ML': {'country': 'Mali', 'ar': True, 'crbt': 0, 'weight': 30},
    'MM': {'country': 'Myanmar', 'ar': False, 'crbt': 0, 'weight': 20},
    'MN': {'country': 'Mongolia', 'ar': True, 'crbt': 0, 'weight': 30},
    'MO': {'country': 'Macau', 'ar': True, 'crbt': 0, 'weight': 30},
    'MP': {'country': 'Northern Mariana Islands', 'ar': False, 'crbt': 0, 'weight': 30},
    'MQ': {'country': 'Martinique (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'MR': {'country': 'Mauritania', 'ar': False, 'crbt': 600, 'weight': 30},
    'MS': {'country': 'Montserrat', 'ar': True, 'crbt': 0, 'weight': 20},
    'MT': {'country': 'Malta', 'ar': True, 'crbt': 0, 'weight': 30},
    'MU': {'country': 'Mauritius', 'ar': True, 'crbt': 0, 'weight': 30},
    'MV': {'country': 'Maldives', 'ar': True, 'crbt': 0, 'weight': 30},
    'MW': {'country': 'Malawi', 'ar': True, 'crbt': 0, 'weight': 30},
    'MX': {'country': 'Mexico', 'ar': True, 'crbt': 0, 'weight': 30},
    'MY': {'country': 'Malaysia', 'ar': False, 'crbt': 0, 'weight': 30},
    'MZ': {'country': 'Mozambique', 'ar': False, 'crbt': 0, 'weight': 20},
    'NA': {'country': 'Namibia', 'ar': True, 'crbt': 0, 'weight': 20},
    'NC': {'country': 'New Caledonia (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'NE': {'country': 'Niger', 'ar': True, 'crbt': 0, 'weight': 30},
    'NF': {'country': 'Norfolk Island', 'ar': False, 'crbt': 0, 'weight': 30},
    'NG': {'country': 'Nigeria', 'ar': True, 'crbt': 0, 'weight': 30},
    'NI': {'country': 'Nicaragua', 'ar': True, 'crbt': 0, 'weight': 20},
    'NL': {'country': 'Netherlands', 'ar': False, 'crbt': 0, 'weight': 30},
    'NO': {'country': 'Norway', 'ar': False, 'crbt': 0, 'weight': 30},
    'NP': {'country': 'Nepal', 'ar': True, 'crbt': 0, 'weight': 20},
    'NR': {'country': 'Nauru', 'ar': False, 'crbt': 0, 'weight': 20},
    'NT': {'country': 'Neutral Zone', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'NU': {'country': 'Niue', 'ar': False, 'crbt': 0, 'weight': 0},
    'NZ': {'country': 'New Zealand', 'ar': False, 'crbt': 0, 'weight': 30},
    'OM': {'country': 'Oman', 'ar': True, 'crbt': 0, 'weight': 20},
    'PA': {'country': 'Panama', 'ar': True, 'crbt': 0, 'weight': 30},
    'PE': {'country': 'Peru', 'ar': False, 'crbt': 0, 'weight': 30},
    'PF': {'country': 'Polynesia (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'PG': {'country': 'Papua New Guinea', 'ar': True, 'crbt': 0, 'weight': 25},
    'PH': {'country': 'Philippines', 'ar': True, 'crbt': 0, 'weight': 20},
    'PK': {'country': 'Pakistan', 'ar': True, 'crbt': 0, 'weight': 30},
    'PL': {'country': 'Poland', 'ar': False, 'crbt': 0, 'weight': 30},
    'PM': {'country': 'Saint Pierre and Miquelon', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'PN': {'country': 'Pitcairn Island', 'ar': False, 'crbt': 0, 'weight': 0},
    'PR': {'country': 'Puerto Rico', 'ar': True, 'crbt': 0, 'weight': 20},
    'PS': {'country': 'Palestinian Territory, Occupied', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'PT': {'country': 'Portugal', 'ar': False, 'crbt': 1000, 'weight': 30},
    'PW': {'country': 'Palau', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'PY': {'country': 'Paraguay', 'ar': True, 'crbt': 0, 'weight': 20},
    'QA': {'country': 'Qatar', 'ar': True, 'crbt': 0, 'weight': 30},
    'RE': {'country': 'Reunion (French)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'RO': {'country': 'Romania', 'ar': True, 'crbt': 0, 'weight': 30},
    'RS': {'country': 'Serbia', 'ar': True, 'crbt': 0, 'weight': 30},
    'RU': {'country': 'Russian Federation', 'ar': True, 'crbt': 0, 'weight': 20},
    'RW': {'country': 'Rwanda', 'ar': True, 'crbt': 0, 'weight': 30},
    'SA': {'country': 'Saudi Arabia', 'ar': True, 'crbt': 0, 'weight': 30},
    'SB': {'country': 'Solomon Islands', 'ar': False, 'crbt': 0, 'weight': 20},
    'SC': {'country': 'Seychelles', 'ar': True, 'crbt': 0, 'weight': 30},
    'SD': {'country': 'Sudan', 'ar': True, 'crbt': 0, 'weight': 30},
    'SE': {'country': 'Sweden', 'ar': False, 'crbt': 0, 'weight': 30},
    'SG': {'country': 'Singapore', 'ar': False, 'crbt': 0, 'weight': 30},
    'SH': {'country': 'Saint Helena', 'ar': False, 'crbt': 0, 'weight': 20},
    'SI': {'country': 'Slovenia', 'ar': True, 'crbt': 0, 'weight': 30},
    'SJ': {'country': 'Svalbard and Jan Mayen Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'SK': {'country': 'Slovakia', 'ar': False, 'crbt': 0, 'weight': 30},
    'SL': {'country': 'Sierra Leone', 'ar': True, 'crbt': 0, 'weight': 30},
    'SM': {'country': 'San Marino', 'ar': True, 'crbt': 1500, 'weight': 20},
    'SN': {'country': 'Senegal', 'ar': True, 'crbt': 600, 'weight': 20},
    'SO': {'country': 'Somalia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'SR': {'country': 'Suriname', 'ar': True, 'crbt': 0, 'weight': 20},
    'SS': {'country': 'South Sudan', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'ST': {'country': 'Saint Tome (Sao Tome) and Principe', 'ar': True, 'crbt': 0, 'weight': 30},
    'SV': {'country': 'El Salvador', 'ar': True, 'crbt': 0, 'weight': 20},
    'SX': {'country': 'Sint Maarten (Dutch part)', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'SY': {'country': 'Syria', 'ar': True, 'crbt': 0, 'weight': 30},
    'SZ': {'country': 'Swaziland', 'ar': True, 'crbt': 0, 'weight': 20},
    'TC': {'country': 'Turks and Caicos Islands', 'ar': False, 'crbt': 0, 'weight': 20},
    'TD': {'country': 'Chad', 'ar': True, 'crbt': 0, 'weight': 30},
    'TF': {'country': 'French Southern Territories', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'TG': {'country': 'Togo', 'ar': True, 'crbt': 600, 'weight': 20},
    'TH': {'country': 'Thailand', 'ar': True, 'crbt': 0, 'weight': 30},
    'TJ': {'country': 'Tajikistan', 'ar': True, 'crbt': 0, 'weight': 20},
    'TK': {'country': 'Tokelau', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'TM': {'country': 'Turkmenistan', 'ar': True, 'crbt': 0, 'weight': 20},
    'TN': {'country': 'Tunisia', 'ar': False, 'crbt': 1500, 'weight': 30},
    'TO': {'country': 'Tonga', 'ar': True, 'crbt': 0, 'weight': 20},
    'TP': {'country': 'East Timor', 'ar': True, 'crbt': 0, 'weight': 20},
    'TR': {'country': 'Turkey', 'ar': False, 'crbt': 1000, 'weight': 30},
    'TT': {'country': 'Trinidad and Tobago', 'ar': False, 'crbt': 0, 'weight': 20},
    'TV': {'country': 'Tuvalu', 'ar': True, 'crbt': 0, 'weight': 20},
    'TW': {'country': 'Taiwan', 'ar': True, 'crbt': 0, 'weight': 20},
    'TZ': {'country': 'Tanzania', 'ar': True, 'crbt': 0, 'weight': 30},
    'UA': {'country': 'Ukraine', 'ar': True, 'crbt': 0, 'weight': 30},
    'UG': {'country': 'Uganda', 'ar': True, 'crbt': 0, 'weight': 30},
    'UM': {'country': 'USA Minor Outlying Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'US': {'country': 'United States', 'ar': False, 'crbt': 0, 'weight': 30},
    'UY': {'country': 'Uruguay', 'ar': False, 'crbt': 0, 'weight': 30},
    'UZ': {'country': 'Uzbekistan', 'ar': True, 'crbt': 0, 'weight': 20},
    'VA': {'country': 'Holy See (Vatican City State)', 'ar': True, 'crbt': 1500, 'weight': 20},
    'VC': {'country': 'Saint Vincent & Grenadines', 'ar': True, 'crbt': 0, 'weight': 10},
    'VE': {'country': 'Venezuela', 'ar': True, 'crbt': 0, 'weight': 30},
    'VG': {'country': 'Virgin Islands (British)', 'ar': False, 'crbt': 0, 'weight': 20},
    'VI': {'country': 'Virgin Islands (USA)', 'ar': False, 'crbt': 0, 'weight': 30},
    'VN': {'country': 'Vietnam', 'ar': True, 'crbt': 0, 'weight': 30},
    'VU': {'country': 'Vanuatu', 'ar': True, 'crbt': 0, 'weight': 25},
    'WF': {'country': 'Wallis and Futuna Islands', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'WS': {'country': 'Samoa', 'ar': True, 'crbt': 0, 'weight': 20},
    'YE': {'country': 'Yemen', 'ar': True, 'crbt': 0, 'weight': 30},
    'YT': {'country': 'Mayotte', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'YU': {'country': 'Yugoslavia', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'ZA': {'country': 'South Africa', 'ar': False, 'crbt': 0, 'weight': 30},
    'ZM': {'country': 'Zambia', 'ar': True, 'crbt': 0, 'weight': 30},
    'ZR': {'country': 'Zaire', 'ar': False, 'product': False, 'crbt': 0, 'weight': 0},
    'ZW': {'country': 'Zimbabwe', 'ar': False, 'crbt': 0, 'weight': 30},
}

postal_code = {
    'AC': {'format': u'', 'control': u'non'},
    'AD': {'format': u'AANNN', 'control': u'sur format'},
    'AD': {'format': u'NNN', 'control': u'sur format'},
    'AE': {'format': u'', 'control': u'non'},
    'AF': {'format': u'NNNN', 'control': u'sur présence'},
    'AG': {'format': u'', 'control': u'non'},
    'AI': {'format': u'', 'control': u'non'},
    'AL': {'format': u'NNNN', 'control': u'sur présence'},
    'AM': {'format': u'NNNN', 'control': u'sur présence'},
    'AN': {'format': u'', 'control': u'non'},
    'AO': {'format': u'', 'control': u'non'},
    'AQ': {'format': u'', 'control': u'non'},
    'AR': {'format': u'ANNNNBBB', 'control': u'sur présence'},
    'AR': {'format': u'NNNN', 'control': u'sur présence'},
    'AS': {'format': u'NNNNN', 'control': u'sur présence'},
    'AT': {'format': u'NNNN', 'control': u'sur présence'},
    'AU': {'format': u'NNNN', 'control': u'sur format'},
    'AW': {'format': u'', 'control': u'non'},
    'AX': {'format': u'NNNNN', 'control': u'sur présence'},
    'AZ': {'format': u'NNNN', 'control': u'sur présence'},
    'BA': {'format': u'NNNNN', 'control': u'sur présence'},
    'BB': {'format': u'', 'control': u'non'},
    'BD': {'format': u'NNNN', 'control': u'sur présence'},
    'BE': {'format': u'NNNN', 'control': u'sur format'},
    'BF': {'format': u'NNNNN', 'control': u'sur présence'},
    'BG': {'format': u'NNNN', 'control': u'sur présence'},
    'BH': {'format': u'NNN', 'control': u'sur présence'},
    'BI': {'format': u'', 'control': u'non'},
    'BJ': {'format': u'NNNN', 'control': u'sur présence'},
    'BM': {'format': u'AANN', 'control': u'sur présence'},
    'BN': {'format': u'AANNNN', 'control': u'sur présence'},
    'BO': {'format': u'', 'control': u'non'},
    'BQ': {'format': u'', 'control': u'non'},
    'BR': {'format': u'NNNNN', 'control': u'sur présence'},
    'BS': {'format': u'', 'control': u'non'},
    'BT': {'format': u'NNNNN', 'control': u'sur présence'},
    'BV': {'format': u'', 'control': u'non'},
    'BW': {'format': u'NNNNN', 'control': u'sur présence'},
    'BY': {'format': u'NNNNNN', 'control': u'sur présence'},
    'BZ': {'format': u'NNNNN', 'control': u'sur présence'},
    'CA': {'format': u'ANANAN', 'control': u'sur présence'},
    'CC': {'format': u'NNNN', 'control': u'sur présence'},
    'CD': {'format': u'NNNNN', 'control': u'sur présence'},
    'CF': {'format': u'NNNNN', 'control': u'sur présence'},
    'CG': {'format': u'NNNNN', 'control': u'sur présence'},
    'CH': {'format': u'NNNN', 'control': u'sur format'},
    'CI': {'format': u'NNNNN', 'control': u'sur présence'},
    'CK': {'format': u'NNNN', 'control': u'sur présence'},
    'CL': {'format': u'NNNNNNN', 'control': u'sur présence'},
    'CM': {'format': u'NNNNN', 'control': u'sur présence'},
    'CN': {'format': u'NNNNNN', 'control': u'sur format'},
    'CO': {'format': u'', 'control': u'non'},
    'CR': {'format': u'NNNNN', 'control': u'sur présence'},
    'CU': {'format': u'NNNNN', 'control': u'sur présence'},
    'CV': {'format': u'NNNN', 'control': u'sur présence'},
    'CX': {'format': u'', 'control': u'non'},
    'CY': {'format': u'NNNN', 'control': u'sur présence'},
    'CZ': {'format': u'NNNNN', 'control': u'sur format'},
    'DE': {'format': u'NNNNN', 'control': u'sur format'},
    'DJ': {'format': u'', 'control': u'non'},
    'DK': {'format': u'NNNN', 'control': u'sur présence'},
    'DM': {'format': u'NNNNN', 'control': u'sur présence'},
    'DO': {'format': u'NNNNN', 'control': u'sur présence'},
    'DZ': {'format': u'NNNNN', 'control': u'sur présence'},
    'EC': {'format': u'NNNNNN', 'control': u'sur présence'},
    'EE': {'format': u'NNNNN', 'control': u'sur format'},
    'EG': {'format': u'NNNNN', 'control': u'sur présence'},
    'EH': {'format': u'NNNNN', 'control': u'sur présence'},
    'ER': {'format': u'NNNNN', 'control': u'sur présence'},
    'ES': {'format': u'NNNNN', 'control': u'sur présence'},
    'ET': {'format': u'NNNN', 'control': u'sur présence'},
    'FI': {'format': u'NNNNN', 'control': u'sur présence'},
    'FJ': {'format': u'NNNNN', 'control': u'sur présence'},
    'FK': {'format': u'AAAANAA', 'control': u'sur présence'},
    'FM': {'format': u'NNNNN', 'control': u'sur présence'},
    'FO': {'format': u'NNN', 'control': u'sur présence'},
    'FR': {'format': u'NNNNN', 'control': u'sur format'},
    'GA': {'format': u'NN', 'control': u'sur présence'},
    'GB': {'format': u'AAN?NAA', 'control': u'sur présence'},
    'GB': {'format': u'ANNAA', 'control': u'sur présence'},
    'GB': {'format': u'A??NAA', 'control': u'sur présence'},
    'GD': {'format': u'', 'control': u'non'},
    'GE': {'format': u'NNNN', 'control': u'sur présence'},
    'GG': {'format': u'AAN?NAA', 'control': u'sur présence'},
    'GG': {'format': u'ANNAA', 'control': u'sur présence'},
    'GG': {'format': u'A??NAA', 'control': u'sur présence'},
    'GH': {'format': u'', 'control': u'non'},
    'GI': {'format': u'', 'control': u'non'},
    'GL': {'format': u'NNNN', 'control': u'sur présence'},
    'GM': {'format': u'', 'control': u'non'},
    'GN': {'format': u'NNNBB', 'control': u'sur présence'},
    'GQ': {'format': u'', 'control': u'non'},
    'GR': {'format': u'NNNNN', 'control': u'sur présence'},
    'GS': {'format': u'AAAANAA', 'control': u'sur présence'},
    'GT': {'format': u'NNNNN', 'control': u'sur présence'},
    'GU': {'format': u'NNNNN', 'control': u'sur présence'},
    'GW': {'format': u'NNNN', 'control': u'sur présence'},
    'GY': {'format': u'NNNNN', 'control': u'sur présence'},
    'HK': {'format': u'', 'control': u'non'},
    'HM': {'format': u'', 'control': u'non'},
    'HN': {'format': u'NNNNN', 'control': u'sur présence'},
    'HR': {'format': u'NNNNN', 'control': u'sur présence'},
    'HT': {'format': u'NNNN', 'control': u'sur présence'},
    'HT': {'format': u'AANNNN', 'control': u'sur présence'},
    'HU': {'format': u'NNNN', 'control': u'sur format'},
    'ID': {'format': u'NNNNN', 'control': u'sur présence'},
    'IE': {'format': u'N', 'control': u'sur présence'},
    'IL': {'format': u'NNNNN', 'control': u'sur présence'},
    'IM': {'format': u'ANNAA', 'control': u'sur présence'},
    'IM': {'format': u'A??NAA', 'control': u'sur présence'},
    'IM': {'format': u'AAN?NAA', 'control': u'sur présence'},
    'IN': {'format': u'NNNNNN', 'control': u'sur présence'},
    'IO': {'format': u'AAAANAA', 'control': u'sur présence'},
    'IQ': {'format': u'NNNNN', 'control': u'sur présence'},
    'IR': {'format': u'NNNNN', 'control': u'sur présence'},
    'IS': {'format': u'NNN', 'control': u'sur présence'},
    'IT': {'format': u'NNNNN', 'control': u'sur présence'},
    'JE': {'format': u'AAN?NAA', 'control': u'sur présence'},
    'JE': {'format': u'ANNAA', 'control': u'sur présence'},
    'JE': {'format': u'A??NAA', 'control': u'sur présence'},
    'JM': {'format': u'', 'control': u'non'},
    'JO': {'format': u'NNNNN', 'control': u'sur présence'},
    'JP': {'format': u'NNNNNNN', 'control': u'sur format'},
    'KE': {'format': u'NNNNN', 'control': u'sur présence'},
    'KG': {'format': u'NNNNNN', 'control': u'sur présence'},
    'KH': {'format': u'NNNNN', 'control': u'sur présence'},
    'KI': {'format': u'', 'control': u'non'},
    'KM': {'format': u'NNNN', 'control': u'sur présence'},
    'KN': {'format': u'', 'control': u'non'},
    'KP': {'format': u'', 'control': u'non'},
    'KR': {'format': u'NNNNNN', 'control': u'sur format'},
    'KW': {'format': u'NNNNN', 'control': u'sur présence'},
    'KY': {'format': u'NNNNN', 'control': u'sur présence'},
    'KZ': {'format': u'NNNNNN', 'control': u'sur présence'},
    'LA': {'format': u'NNNNN', 'control': u'sur présence'},
    'LB': {'format': u'', 'control': u'non'},
    'LC': {'format': u'', 'control': u'non'},
    'LI': {'format': u'NNNN', 'control': u'sur présence'},
    'LK': {'format': u'NNNNN', 'control': u'sur présence'},
    'LR': {'format': u'NNNN', 'control': u'sur présence'},
    'LS': {'format': u'NNN', 'control': u'sur présence'},
    'LT': {'format': u'NNNNN', 'control': u'sur format'},
    'LU': {'format': u'NNNN', 'control': u'sur présence'},
    'LV': {'format': u'NNNN', 'control': u'sur format'},
    'LY': {'format': u'NNNNN', 'control': u'sur présence'},
    'MA': {'format': u'NNNNN', 'control': u'sur présence'},
    'MC': {'format': u'NNNNN', 'control': u'sur format'},
    'MD': {'format': u'NNNN', 'control': u'sur présence'},
    'ME': {'format': u'NNNNN', 'control': u'sur présence'},
    'MG': {'format': u'NNN', 'control': u'sur présence'},
    'MH': {'format': u'', 'control': u'non'},
    'MK': {'format': u'NNNN', 'control': u'sur présence'},
    'ML': {'format': u'', 'control': u'non'},
    'MM': {'format': u'NNNNN', 'control': u'sur présence'},
    'MN': {'format': u'NNNNN', 'control': u'sur présence'},
    'MO': {'format': u'', 'control': u'non'},
    'MP': {'format': u'', 'control': u'non'},
    'MR': {'format': u'', 'control': u'non'},
    'MS': {'format': u'', 'control': u'non'},
    'MT': {'format': u'AAANNNN', 'control': u'sur présence'},
    'MU': {'format': u'NNNAA', 'control': u'sur présence'},
    'MV': {'format': u'NNNNN', 'control': u'sur présence'},
    'MW': {'format': u'', 'control': u'non'},
    'MX': {'format': u'NNNNN', 'control': u'sur présence'},
    'MY': {'format': u'NNNNN', 'control': u'sur présence'},
    'MZ': {'format': u'NNNN', 'control': u'sur présence'},
    'NA': {'format': u'', 'control': u'non'},
    'NE': {'format': u'NNNN', 'control': u'sur présence'},
    'NF': {'format': u'', 'control': u'non'},
    'NG': {'format': u'NNNNNN', 'control': u'sur présence'},
    'NI': {'format': u'NNNNNNN', 'control': u'sur présence'},
    'NL': {'format': u'NNNNAA', 'control': u'sur présence'},
    'NO': {'format': u'NNNN', 'control': u'sur présence'},
    'NP': {'format': u'NNNNN', 'control': u'sur présence'},
    'NR': {'format': u'', 'control': u'non'},
    'NU': {'format': u'', 'control': u'non'},
    'NZ': {'format': u'NNNN', 'control': u'sur présence'},
    'OM': {'format': u'NNN', 'control': u'sur présence'},
    'PA': {'format': u'', 'control': u'non'},
    'PE': {'format': u'NNNNN', 'control': u'sur présence'},
    'PG': {'format': u'NNN', 'control': u'sur présence'},
    'PH': {'format': u'NNNN', 'control': u'sur présence'},
    'PK': {'format': u'NNNNN', 'control': u'sur présence'},
    'PL': {'format': u'NNNNN', 'control': u'sur format'},
    'PN': {'format': u'AAAANAA', 'control': u'sur présence'},
    'PR': {'format': u'NNNNN', 'control': u'sur présence'},
    'PS': {'format': u'NNNNN', 'control': u'sur présence'},
    'PT': {'format': u'NNNNNNN', 'control': u'sur format'},
    'PW': {'format': u'NNNNN', 'control': u'sur présence'},
    'PY': {'format': u'NNNN', 'control': u'sur présence'},
    'QA': {'format': u'', 'control': u'non'},
    'RO': {'format': u'NNNNNN', 'control': u'sur présence'},
    'RS': {'format': u'NNNNN', 'control': u'sur présence'},
    'RU': {'format': u'NNNNNN', 'control': u'sur présence'},
    'RW': {'format': u'', 'control': u'non'},
    'SA': {'format': u'NNNNN', 'control': u'sur présence'},
    'SB': {'format': u'', 'control': u'non'},
    'SC': {'format': u'', 'control': u'non'},
    'SD': {'format': u'NNNNN', 'control': u'sur présence'},
    'SE': {'format': u'NNNNN', 'control': u'sur présence'},
    'SG': {'format': u'NNNNNN', 'control': u'sur format'},
    'SH': {'format': u'AAAANAA', 'control': u'sur présence'},
    'SI': {'format': u'NNNN', 'control': u'sur format'},
    'SJ': {'format': u'NNNN', 'control': u'sur présence'},
    'SK': {'format': u'NNNNN', 'control': u'sur format'},
    'SL': {'format': u'', 'control': u'non'},
    'SM': {'format': u'NNNNN', 'control': u'sur présence'},
    'SN': {'format': u'NNNNN', 'control': u'sur présence'},
    'SO': {'format': u'AANNNNN', 'control': u'sur présence'},
    'SR': {'format': u'', 'control': u'non'},
    'SS': {'format': u'NNNNN', 'control': u'sur présence'},
    'ST': {'format': u'', 'control': u'non'},
    'SV': {'format': u'', 'control': u'non'},
    'SX': {'format': u'', 'control': u'non'},
    'SY': {'format': u'NNNN', 'control': u'sur présence'},
    'SZ': {'format': u'ANNN', 'control': u'sur présence'},
    'S1': {'format': u'NNNNN', 'control': u'sur format'},
    'TC': {'format': u'AAAANAA', 'control': u'sur présence'},
    'TD': {'format': u'', 'control': u'non'},
    'TG': {'format': u'', 'control': u'non'},
    'TH': {'format': u'NNNNN', 'control': u'sur présence'},
    'TJ': {'format': u'NNNNNN', 'control': u'sur présence'},
    'TK': {'format': u'NNNN', 'control': u'sur présence'},
    'TL': {'format': u'', 'control': u'non'},
    'TM': {'format': u'NNNNNN', 'control': u'sur présence'},
    'TN': {'format': u'NNNN', 'control': u'sur présence'},
    'TO': {'format': u'', 'control': u'non'},
    'TR': {'format': u'NNNNN', 'control': u'sur présence'},
    'TT': {'format': u'NNNNN', 'control': u'sur présence'},
    'TV': {'format': u'', 'control': u'non'},
    'TW': {'format': u'NNN', 'control': u'sur présence'},
    'TW': {'format': u'NNNNN', 'control': u'sur présence'},
    'TZ': {'format': u'', 'control': u'non'},
    'T2': {'format': u'', 'control': u'non'},
    'UA': {'format': u'NNNNN', 'control': u'sur présence'},
    'UG': {'format': u'', 'control': u'non'},
    'UM': {'format': u'', 'control': u'non'},
    'US': {'format': u'NNNNN', 'control': u'sur format'},
    'UY': {'format': u'NNNNN', 'control': u'sur présence'},
    'UZ': {'format': u'NNNNNN', 'control': u'sur présence'},
    'VA': {'format': u'NNNNN', 'control': u'sur présence'},
    'VC': {'format': u'', 'control': u'non'},
    'VE': {'format': u'NNNN', 'control': u'sur présence'},
    'VG': {'format': u'NNNN', 'control': u'sur présence'},
    'VG': {'format': u'AANNNN', 'control': u'sur présence'},
    'VI': {'format': u'NNNNN', 'control': u'sur présence'},
    'VN': {'format': u'NNNNNN', 'control': u'sur présence'},
    'VU': {'format': u'NNNNN', 'control': u'sur présence'},
    'WS': {'format': u'', 'control': u'non'},
    'XZ': {'format': u'', 'control': u'non'},
    'YE': {'format': u'NNNNN', 'control': u'sur présence'},
    'ZA': {'format': u'NNNN', 'control': u'sur présence'},
    'ZM': {'format': u'NNNNN', 'control': u'sur présence'},
    'ZW': {'format': u'', 'control': u'non'}
}
